# tasks file for percona-client
---
- name: install | dependencies
  apt:
    name: "{{ percona_client_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - percona-client-install-dependencies

- name: install | additional
  apt:
    name: "{{ percona_client_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - percona-client-install-additional
