# tasks file for percona-client
---
- name: install | dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ percona_client_dependencies }}"
  tags:
    - percona-client-install-dependencies

- name: install | additional
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ percona_client_install }}"
  tags:
    - percona-client-install-additional
