# tasks file
---
- name: install | dependencies
  ansible.builtin.apt:
    name: "{{ percona_client_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - percona-client-install-dependencies

- name: install | additional
  ansible.builtin.apt:
    name: "{{ percona_client_install }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - percona-client-install-additional
