# tasks file for percona-client
---
- include: repository.yml
  tags:
    - configuration
    - percona-client
    - percona-client-repository

- include: install.yml
  tags:
    - configuration
    - percona-client
    - percona-client-install

- include: configure.yml
  tags:
    - configuration
    - percona-client
    - percona-client-configure
