# tasks file
---
- include: version-support.yml
  tags:
    - configuration
    - percona-client
    - percona-client-version-support

- include: repository.yml
  tags:
    - configuration
    - percona-client
    - percona-client-repository

- include: install.yml
  tags:
    - configuration
    - percona-client
    - percona-client-install

- include: configure.yml
  tags:
    - configuration
    - percona-client
    - percona-client-configure
