# tasks file
---
- name: version support
  ansible.builtin.import_tasks: version-support.yml
  tags:
    - configuration
    - percona-client
    - percona-client-version-support

- name: repository
  ansible.builtin.import_tasks: repository.yml
  tags:
    - configuration
    - percona-client
    - percona-client-repository

- name: install
  ansible.builtin.import_tasks: install.yml
  tags:
    - configuration
    - percona-client
    - percona-client-install

- name: configure
  ansible.builtin.import_tasks: configure.yml
  tags:
    - configuration
    - percona-client
    - percona-client-configure
