# tasks file for percona-client
---
- name: repository | add public key
  apt_key:
    id: CD2EFD2A
    url: http://www.percona.com/downloads/RPM-GPG-KEY-percona
    state: present
  tags:
    - percona-client-repository-public-key

- name: repository | add
  apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: present
    update_cache: yes
  with_items: percona_client_repositories
  tags:
    - percona-client-repository-add

- name: repository | apt-pin packages
  copy:
    src: etc/apt/preferences.d/00percona.pref
    dest: /etc/apt/preferences.d/00percona.pref
    owner: root
    group: root
    mode: 0644
  tags:
    - percona-client-repository-apt-pin
